# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"
#remote_theme: "mmistakes/minimal-mistakes@4.16.6"
#minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

# Site Settings
locale                   : "en-US"
title                    : "Testing Cube Center"
title_separator          : "-"
subtitle                 : "what can possibly go wrong?"
name                     : "naTrent"
description              : "Simple blog about my journey with testing ang Quality Assurance."
url                      : # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : "/assets/images/teaser.jpg"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200







# Author Information
author:
  name: naTrent
  avatar: "https://api.adorable.io/avatars/285/miki@adorable.io.png"
  bio: "My awesome biography constrained to a sentence or two goes here."
  location: "Warszawa, Poland"
  twitter: Mikstan1
  github: natrent
twitter_username: Mikstan1
github_username: natrent

# Search Engine
search: true
search_full_content: true
search_provider: algolia
algolia:
  application_id: QB6HVGBSBA
  index_name: basically-basic
  search_only_api_key: 9d5014e5bbc77372547bce778dfa5663

# Liquid
liquid:
  error_mode: strict

# Build theme settings
markdown: kramdown
gem "github-pages", group: :jekyll_plugins
##remote_theme: "mmistakes/jekyll-theme-basically-basic"

breadcrumbs: true  # disabled by default
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
feed:
  path: atom.xml

# Posts configuration
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
#        comments: true
      share: true
      related: true
# Page Images

##header:
##  teaser: /assets/images/teaser.jpg

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Google Analytics
google_analytics: UA-148161437-1

