# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-US
title: Testing Cube Center
email: testcube101@gmail.com
description: "Simple blog about my journey with testing ang Quality Assurance"
# baseurl: "/blog.md"

# Author Information
author:
  name: naTrent
  avatar: "https://api.adorable.io/avatars/285/miki@adorable.io.png"
  bio: "My awesome biography constrained to a sentence or two goes here."
  location: "Warszawa, Poland"
  twitter: Mikstan1
twitter_username: Mikstan1
github_username: natrent

# Search Engine
search: true
search_full_content: true
search_provider: algolia
algolia:
  application_id: QB6HVGBSBA
  index_name: basically-basic
  search_only_api_key: 9d5014e5bbc77372547bce778dfa5663

# Liquid
liquid:
  error_mode: strict

# Build theme settings
markdown: kramdown
gem "github-pages", group: :jekyll_plugins
##remote_theme: "mmistakes/jekyll-theme-basically-basic"
remote_theme: "mmistakes/minimal-mistakes@4.16.6"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"
breadcrumbs: true  # disabled by default
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
feed:
  path: atom.xml

defaults:
  _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
        author_profile: true
        read_time: true
        comments: true
        share: true
        related: true

# Page Images
teaser: /assets/images/500x300.png
header:
  teaser: /assets/images/my-awesome-post-teaser.jpg

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Google Analytics
google_analytics: UA-148161437-1

